namespace: santiago-parraga-dev

names:
  app: "microservicio-2"
  deployment: "mi-deployment-2"
  service: "mi-servicio-2"
  configmap: "mi-configmap-2"
  secret: "mi-secret-2"
  hpa: "mi-hpa-2"
  pvc: "mi-pvc-2"

replicaCount: 1

image:
  repository: santiagoparraga/holamundobasespm2
  tag: "{{ tag }}"        # cambia aquí tu build
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: "500m"
    memory: "800Mi"
  limits:
    cpu: "800m"
    memory: "1500Mi"

probes:
  startup:
    path: /startup
    port: 8080
    failureThreshold: 10
    periodSeconds: 5
  readiness:
    path: /readiness
    port: 8080
    initialDelaySeconds: 0
    periodSeconds: 5
    failureThreshold: 3
    timeoutSeconds: 2
  liveness:
    path: /health
    port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 2

configmap:
  enabled: true
  data:
    DATABASE: "192.168.1.1"

secret:
  enabled: true
  stringData:
    PASSWORD: "hola"     # cambia si quieres (aG9sYQ== = "hola")
    
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

storage:
  enabled: true
  volumeName: "datos" 
  mountPath: "/app/data"
  size: "1Gi"
  storageClassName: "gp3"
  accessModes:
    - ReadWriteOnce
